uninstall gcc packages after instalation
itential/itential.deployer pull request #105
Opened 2024-12-04 15:11 UTC by Nick-Andreano

2024-12-04 18:23 UTC, steven-schattenberg-itential submitted a review, later dismissed

2024-12-04 20:19 UTC, kvelarde-itential commented
Do we care about a scenario where a customer installed gcc?  Would it be more "correct" to capture the output of the install step and only uninstall if it was installed by the Deployer?

2024-12-04 20:22 UTC, kvelarde-itential commented on roles/redis/tasks/main.yml
> +    - gcc-c++
Should we use `redis_build_packages` here?

2024-12-04 20:22 UTC, kvelarde-itential commented on roles/gateway/tasks/main.yml
> +    - gcc-c++
Should we create a new var called `gateway_build_packages` similar to the redis role and uninstall those packages instead?

2025-01-03 20:18 UTC, kvelarde-itential requested changes

2025-01-03 20:18 UTC, kvelarde-itential commented on roles/redis/tasks/main.yml
> +- name: Uninstall gcc packages
```suggestion
- name: Uninstall redis build packages
```

2025-01-03 20:18 UTC, kvelarde-itential commented on roles/redis/tasks/main.yml
> +  with_items: "{{ redis_build_packages[ansible_distribution_major_version] }}"
```suggestion
  with_items: "{{ redis_build_packages[ansible_distribution_major_version] }}"
  when: redis_install_method == "source"
```

2025-01-03 20:18 UTC, kvelarde-itential commented on roles/redis/tasks/main.yml
> +  with_items: "{{ redis_build_packages[ansible_distribution_major_version] }}"
I think this task should only run when we're installing from source.

2025-01-03 21:46 UTC, kvelarde-itential approved these changes

2025-01-06 18:09 UTC, merged